// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  main

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( Employee ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* Employee ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_Employee *Employee
